"""Selectable chat providers (DeepSeek, OpenAI) and OpenAI embeddings."""

from deep_research.providers.capabilities import (
    ModelCapability,
    ResolvedRequestSettings,
    capability_for,
    resolve_request_settings,
)
from deep_research.providers.contracts import (
    ChatMessage,
    ChatResult,
    FinishReasonCategory,
    OpenAIProviderError,
    ProviderConfigurationError,
    ProviderError,
    ProviderFailureCategory,
    ProviderFailureKind,
    ProviderFailureSnapshot,
    ProviderOutputLimitError,
    ProviderRateLimitError,
    ProviderResponseError,
    ProviderResponseTelemetry,
    ProviderTimeoutError,
    StructuredDiagnosticCategory,
    StructuredOutputError,
    StructuredValidationDiagnostic,
    provider_failure_snapshot,
)
from deep_research.providers.deepseek_provider import (
    DEEPSEEK_BASE_URL,
    DeepSeekChatProvider,
    DeepSeekJudgeProvider,
)
from deep_research.providers.embedding_capabilities import (
    EmbeddingModelCapability,
    embedding_capability_for,
)
from deep_research.providers.embeddings import (
    DEFAULT_EMBEDDING_MODEL,
    LOCAL_EMBEDDING_DIMENSION,
    LOCAL_EMBEDDING_PROVIDER,
    LocalEmbeddingProvider,
    OpenAIEmbeddingProvider,
)
from deep_research.providers.factory import (
    ChatAdapter,
    EmbeddingAdapter,
    JudgeAdapter,
    build_chat_provider,
    build_embedding_provider,
    build_judge_provider,
    validate_agent_model_configs,
)
from deep_research.providers.openai_provider import OpenAIChatProvider

__all__ = [
    "ChatAdapter",
    "ChatMessage",
    "ChatResult",
    "DEEPSEEK_BASE_URL",
    "DEFAULT_EMBEDDING_MODEL",
    "DeepSeekChatProvider",
    "DeepSeekJudgeProvider",
    "EmbeddingAdapter",
    "EmbeddingModelCapability",
    "JudgeAdapter",
    "LOCAL_EMBEDDING_DIMENSION",
    "LOCAL_EMBEDDING_PROVIDER",
    "LocalEmbeddingProvider",
    "ModelCapability",
    "OpenAIChatProvider",
    "OpenAIEmbeddingProvider",
    "OpenAIProviderError",
    "FinishReasonCategory",
    "ProviderConfigurationError",
    "ProviderError",
    "ProviderFailureCategory",
    "ProviderFailureKind",
    "ProviderFailureSnapshot",
    "ProviderOutputLimitError",
    "ProviderRateLimitError",
    "ProviderResponseError",
    "ProviderResponseTelemetry",
    "ProviderTimeoutError",
    "StructuredDiagnosticCategory",
    "ResolvedRequestSettings",
    "StructuredValidationDiagnostic",
    "StructuredOutputError",
    "build_chat_provider",
    "build_embedding_provider",
    "build_judge_provider",
    "capability_for",
    "embedding_capability_for",
    "resolve_request_settings",
    "validate_agent_model_configs",
    "provider_failure_snapshot",
]
